/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "stats.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static int *
_search_1 (search_1_argument *argp, struct svc_req *rqstp)
{
	return (search_1_svc(argp->arg1, argp->arg2, rqstp));
}

static int *
_zero_1 (zero_1_argument *argp, struct svc_req *rqstp)
{
	return (zero_1_svc(argp->arg1, argp->arg2, rqstp));
}

static int *
_sum_1 (DATA  *argp, struct svc_req *rqstp)
{
	return (sum_1_svc(*argp, rqstp));
}

static int *
_median_1 (DATA  *argp, struct svc_req *rqstp)
{
	return (median_1_svc(*argp, rqstp));
}

static int *
_average_1 (DATA  *argp, struct svc_req *rqstp)
{
	return (average_1_svc(*argp, rqstp));
}

static int *
_stdev_1 (DATA  *argp, struct svc_req *rqstp)
{
	return (stdev_1_svc(*argp, rqstp));
}

static void
statsprog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		search_1_argument search_1_arg;
		zero_1_argument zero_1_arg;
		DATA sum_1_arg;
		DATA median_1_arg;
		DATA average_1_arg;
		DATA stdev_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case search:
		_xdr_argument = (xdrproc_t) xdr_search_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _search_1;
		break;

	case zero:
		_xdr_argument = (xdrproc_t) xdr_zero_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _zero_1;
		break;

	case sum:
		_xdr_argument = (xdrproc_t) xdr_DATA;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _sum_1;
		break;

	case median:
		_xdr_argument = (xdrproc_t) xdr_DATA;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _median_1;
		break;

	case average:
		_xdr_argument = (xdrproc_t) xdr_DATA;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _average_1;
		break;

	case STDEV:
		_xdr_argument = (xdrproc_t) xdr_DATA;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _stdev_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (STATSPROG, STATSVERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, STATSPROG, STATSVERS, statsprog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (STATSPROG, STATSVERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, STATSPROG, STATSVERS, statsprog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (STATSPROG, STATSVERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
